baseurl = "https://gvarchala-pixel.github.io/"
title = "My Findings & Learnings"
theme = "hugo-theme-cleanwhite"
languageCode = "en-us"
preserveTaxonomyNames = true

[pagination]
  pagerSize = 5

[outputs]
  home = ["HTML", "RSS"]

[params]
  header_image = "img/home-bg-jeep.jpg"
  SEOTitle = "My Findings & Learnings"
  description = "A personal blog documenting my findings, learnings, and explorations."
  keyword = "blog, findings, learnings, technology, development"
  slogan = "Curiosity-driven learning, one post at a time."
  upstreamAttribution = true

  image_404 = "img/404-bg.jpg"
  title_404 = "Oops! Nothing to find here :("
  omit_categories = false

  # Disable analytics & comment services
  page_view_counter = false
  algolia_search = false

  # Sidebar settings
  sidebar_about_description = "Curious learner, sharing findings and explorations."
  sidebar_avatar = "img/avatar.png"  # Add your avatar image to static/img/

  featured_tags = true
  featured_condition_size = 1

  reward = false
  friends = false
  bookmarks = false
  about_me = true

  # Last posts
  last_posts = true

  [params.social]
    rss    = true
    github = "https://github.com/gvarchala-pixel"

  [[params.additional_menus]]
    title = "ARCHIVE"
    href  = "/archive/"

  [[params.additional_menus]]
    title = "TAGS"
    href  = "/tags/"

  [[params.additional_menus]]
    title = "ABOUT"
    href  = "/about/"

[markup]
  [markup.tableOfContents]
    endLevel = 3
    startLevel = 1
  [markup.highlight]
    style = "dracula"
    codeFences = true
    guessSyntax = true
    lineNos = true
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
